name: CI

on: push

jobs:
  rspec:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} RSpec
    strategy:
      matrix:
        ruby:
          - '3.2'
          - '3.3'
          - '3.4'
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby }}
    - run: bundle exec rspec

  rubocop:
    runs-on: ubuntu-latest
    name: RuboCop
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: '3.4'
    - run: bundle exec rubocop
